### PR TITLE
FOGL-7962 - New audit log codes for ACL and Control Script and pipeline

### PR DESCRIPTION
**Pull request by ashish-jabble**

### CODE REVIEW

**Review by MarkRiddoch — DISMISSED** [review]
I suggest Massimilaino take a look at this as he will need it for the local changes feature on FogLAMP Manage

**Comment by ashish-jabble** [comment]
@pintomax As this change is required only for FogLAMP Manage to detect local changes. Please have a look. This is awaiting from your side.

**Comment by pintomax** [comment]
@ashish-jabble I see this with entity removed

CTPDL { "message": "Control Pipeline with ID:<3> has been deleted successfully." }
ACLDL { "message": "A1 ACL deleted successfully." }
CTSDL { "message": "SC1 script deleted successfully." }

We also need "name" in the JSON data for easy and exact parsing of entity name


You can either add "name" or remove " message" and only use "name"

Example, Notification delete:

NTFDL {"name":"N2"}

**Review by pintomax — CHANGES_REQUESTED** [review]
We need "name" in the JSON data for CTPDL, CTSDL, ACLDL for parsing actions

**Comment by ashish-jabble** [comment]
@pintomax *name* KV pair added in delete audit log codes.
```
CTPDL	{ "name": "CP1", "message": "Control Pipeline with ID:<1> has been deleted successfully." }
ACLDL	{ "name": "ACL1", "message": "ACL1 ACL deleted successfully." }
CTSDL	{ "name": "SC1", "message": "SC1 script deleted successfully." }
```

**Review by pintomax — APPROVED** [review]

**Pull request merged**
