### PR TITLE
FOGL-5006 Add documentation for built in rule and OMF

### PR DESCRIPTION
**Pull request by MarkRiddoch**
Signed-off-by: Mark Riddoch <mark@dianomic.com>

### CODE REVIEW

**Review by YashTatkondawar — COMMENTED** [review]
@MarkRiddoch I have created the docs from [FOGL-5006 branch](https://fledge-iot.readthedocs.io/en/fogl-5006-test/plugin_index.html) and with your changes the plugin_index page looks very different from what we had with [1.9.0RC branch](https://fledge-iot.readthedocs.io/en/1.9.0rc/plugin_index.html#). It looks incorrect to me, please have a look.
Also the issue with [OMF](https://fledge-iot.readthedocs.io/en/fogl-5006-test/fledge-north-OMF.html) doc link is still there.

**Comment by MarkRiddoch** [comment]
> @MarkRiddoch I have created the docs from [FOGL-5006 branch](https://fledge-iot.readthedocs.io/en/fogl-5006-test/plugin_index.html) and with your changes the plugin_index page looks very different from what we had with [1.9.0RC branch](https://fledge-iot.readthedocs.io/en/1.9.0rc/plugin_index.html#). It looks incorrect to me, please have a look.
> Also the issue with [OMF](https://fledge-iot.readthedocs.io/en/fogl-5006-test/fledge-north-OMF.html) doc link is still there.

Not sure what you have done to pull in the plugin repositories, they should not be coming from the FOGL-5006 branch, When I do a local build I get everything. are there any errors logged when you do your run?

**Comment by YashTatkondawar** [comment]
> Not sure what you have done to pull in the plugin repositories, they should not be coming from the FOGL-5006 branch, When I do a local build I get everything. are there any errors logged when you do your run?

Yes, if I want to create docs from FOGL-5006 so this branch is expected in every repository and that is the reason all repos docs were not created. As I was assuming it wrong so we can ignore the below issue 

>  I have created the docs from FOGL-5006 branch and with your changes the plugin_index page looks very different from what we had with 1.9.0RC branch. It looks incorrect to me, please have a look.

But I am trying to build the docs on readthedocs server from  FOGL-5006 branch and there I am getting following error logs:
```
/home/docs/checkouts/readthedocs.org/user_builds/fledge-iot/checkouts/fogl-5006-test/docs
scripts/plugin_documentation: line 110: fledge-north-omf.rst: No such file or directory
cp: cannot stat '../fledge-rule-Threshold/*': No such file or directory 
```
So could you please have a look?

**Comment by YashTatkondawar** [comment]
@MarkRiddoch Could you please update FOGL-5006 branch with develop branch.

**Review by YashTatkondawar — COMMENTED** [review]
In the docs that I created from the FOGL-5006 branch I am seeing fledge-north-OMF.html instead  it should have been fledge-north-OMF/index.html. Not sure if I am missing anything. Could you please have a look and check?

**Review by YashTatkondawar — APPROVED** [review]

**Pull request merged**
