### PR TITLE
FOGL-8087: fix for statistics rate in Postgres

### PR DESCRIPTION
**Pull request by pintomax**
FOGL-8087: fix for statistics rate in Postgres
Also fixes FOGL-4102

Note: FOGL-7960 should be fixed as well

### CODE REVIEW

**Review by hemantgarg923 — COMMENTED** [review]
This PR has fixed FOGL-8087 but not FOGL-7960 & FOGL-4102. As mentioned in the ticket FOGL-7960, output of the API [http://localhost:8081/foglamp/statistics/rate?statistics=sin1-Ingest&periods=1,10](http://localhost:8081/foglamp/statistics/rate?statistics=sin1-Ingest&periods=1,10) is not constant, it keeps increasing.
On Postgres output of the curl is:

`curl -X PUT http://192.168.43.7:41007/storage/table/statistics_history/query -d @/home/vboxuser/payload.json | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   492  100   209  100   283   5500   7447 --:--:-- --:--:-- --:--:-- 14909
{
  "entryPoint": "retrieve",
  "message": "ERROR:  syntax error at or near \"END\"LINE 1: SELECT sum(\"value\" END) AS \"sum_value\", count(\"value\" END) A...                           ^",
  "retryable": false
}`

**Comment by pintomax** [comment]
> This PR has fixed FOGL-8087 but not FOGL-7960 & FOGL-4102. As mentioned in the ticket FOGL-7960, output of the API http://localhost:8081/foglamp/statistics/rate?statistics=sin1-Ingest&periods=1,10 is not constant, it keeps increasing.
> 
> On Postgres output of the curl is:
> 
> `curl -X PUT http://192.168.43.7:41007/storage/table/statistics_history/query -d @/home/vboxuser/payload.json | jq % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 100 492 100 209 100 283 5500 7447 --:--:-- --:--:-- --:--:-- 14909 { "entryPoint": "retrieve", "message": "ERROR: syntax error at or near \"END\"LINE 1: SELECT sum(\"value\" END) AS \"sum_value\", count(\"value\" END) A... ^", "retryable": false }`

@hemantgarg923 You said this fixed FOGL-8087 
What is the issue with above curl? Is it about another test?

please add the payload.json here

**Comment by hemantgarg923** [comment]
Payload.json : 
`{"return": ["key"], "aggregate": [{"operation": "sum", "column": "value"}, {"operation": "count", "column": "value"}], "where": {"column": "history_ts", "condition": ">=", "value": "1590126369.123255", "and": {"column": "key", "condition": "=", "value": "READINGS"}}, "group": "key"}`

It is also available in jira [https://scaledb.atlassian.net/browse/FOGL-4102](https://scaledb.atlassian.net/browse/FOGL-4102)

**Review by cyberwalk3r — APPROVED** [review]

**Review by MarkRiddoch — APPROVED** [review]
Please sign the commit

**Comment by cyberwalk3r** [comment]
> FOGL-8087: fix for statistics rate in Postgres Also fixes FOGL-4102
> 
> Note: FOGL-7960 should be fixed as well

With this fix for Postgres, incorrect values returned (in sqlite and postgres) for statistics rate [FOGL-7960](https://scaledb.atlassian.net/browse/FOGL-7960) also need a fix for Flow Monitoring functionality to work.

**Pull request merged**
