### PR TITLE
FOGL-7579 package name handling in Plugins PUT & DELETE API

### PR DESCRIPTION
**Pull request by ashish-jabble**
~Note: I haven't changed the param in request - name Vs PackageName. So we need to decide for the backward compatability by checking fledge core version `check > 2.1.0`; as this endpoint is only use by FogLAMP Manage.~

~As this endpoint is to update the package. So we should request with package name to make more clarity in the endpoint.~

New endpoints available with 2.1.0 onwards core version. More, details added on JIRA
```
PUT /fledge/plugins/{package_name}
DELETE /fledge/plugins/{package_name}
```

### CODE REVIEW

**Comment by pintomax** [comment]
@ashish-jabble If we keep existing API endpoint for PUT and delete, then FogLAMP manage will work without any instance version check.

Otherwise, a change for PUT and DELETE requires deployment code change in order to call old and new endpoint based on instance version > 2.1.0

This requires some work and tests: if it's worth it then we can do it.

**Comment by pintomax** [comment]
@ashish-jabble in case of API endpoint change I think it's better to use

PUT          /fledge/plugins/fledge-south-modbus/update             (Without plugin type)
DELETE    /fledge/plugins/fledge-south-modbus                          (Without plugin type)

**Comment by MarkRiddoch** [comment]
It makes sense to use the same convention as with the POST call to install a package.

**Comment by ashish-jabble** [comment]
@MarkRiddoch 
> It makes sense to use the same convention as with the POST call to install a package.

Shall I go ahead to change the API URL for PUT & DELETE? ?

```
PUT /fledge/plugins/fledge-south-modbus
DELETE /fledge/plugins/fledge-south-modbus
```
Also, please confirm do we really need to handle backward compatibility of the API URL at Admin API side with the `fledge core version > 2.1.0`?

**Comment by pintomax** [comment]
> @MarkRiddoch
> 
> > It makes sense to use the same convention as with the POST call to install a package.
> 
> Shall I go ahead to change the API URL for PUT & DELETE? ?
> 
> ```
> PUT /fledge/plugins/fledge-south-modbus
> DELETE /fledge/plugins/fledge-south-modbus
> ```
> 
> Also, please confirm do we really need to handle backward compatibility of the API URL at Admin API side with the `fledge core version > 2.1.0`?

The PUT API shouldn't it be PUT /fledge/plugins/fledge-south-modbus/update ?

**Comment by MarkRiddoch** [comment]
> @MarkRiddoch
> 
> > It makes sense to use the same convention as with the POST call to install a package.
> 
> Shall I go ahead to change the API URL for PUT & DELETE? ?
> 
> ```
> PUT /fledge/plugins/fledge-south-modbus
> DELETE /fledge/plugins/fledge-south-modbus
> ```
> 
> Also, please confirm do we really need to handle backward compatibility of the API URL at Admin API side with the `fledge core version > 2.1.0`?

Yes please

**Review by pintomax — DISMISSED** [review]

**Comment by ashish-jabble** [comment]
Hi @MarkRiddoch Shall we merge this into develop branch?

**Comment by MarkRiddoch** [comment]
> Hi @MarkRiddoch Shall we merge this into develop branch?

Yes, I think so

**Pull request merged**
