### PR TITLE
FOGL-6495: POST API fix for new delivery channel

### PR DESCRIPTION
**Pull request by pintomax**
FOGL-6495: POST API fix for new delivery channel

### CODE REVIEW

**Comment by mshariq-nerd** [comment]
@pintomax  
Testing result 
Let say **N1** is a notification instance name 
1. With invalid payload
```
curl -sX POST http://localhost:8081/fledge/notification/N1/delivery -d '{"name": "coolant", "config": {"action": {"description": "Perform a control action to turn pump", "type": "boolean", "default": "false"}}}' | jq
{
  "message": "'plugin' property is missing or not a JSON object in 'config' data"
}
```
2.  With valid payload

 ```
curl -sX POST http://localhost:8081/fledge/notification/N1/delivery -d '{"name": "coolant", "config": {"action": {"description": "Perform a control action to turn pump", "type": "boolean", "default": "false"}, "plugin": {"description": "asset plugin","type": "string","readonly": "true","default": "asset"}}}' | jq
{
  "category": "N1_channel_coolant",
  "description": "coolant delivery channel",
  "config": {
    "action": {
      "description": "Perform a control action to turn pump",
      "type": "boolean",
      "default": "false"
    },
    "plugin": {
      "description": "asset plugin",
      "type": "string",
      "readonly": "true",
      "default": "asset"
    }
  }
}
```

Channel **coolant** successfully created but **FATAL** in syslog and notification service moves into unresponsive state 

```
Jun 17 18:56:33 fledge-VirtualBox Fledge Fledge notification[19382]: FATAL: Signal 6 (Aborted) trapped:
Jun 17 18:56:33 fledge-VirtualBox Fledge Fledge notification[19382]: FATAL: (0) 0       0x55ea269bd089 handler(int) + 73---------
Jun 17 18:56:33 fledge-VirtualBox Fledge Fledge notification[19382]: FATAL: (1) 1       0x7f4a000cdf10 /lib/x86_64-linux-gnu/libc.so.6(+0x3ef10) [0x7f4a000cdf10]---------
Jun 17 18:56:33 fledge-VirtualBox Fledge Fledge notification[19382]: FATAL: (2) 2       0x7f4a000cde87 gsignal + 199---------
Jun 17 18:56:33 fledge-VirtualBox Fledge Fledge notification[19382]: FATAL: (3) 3       0x7f4a000cf7f1 abort + 321---------
Jun 17 18:56:33 fledge-VirtualBox Fledge Fledge notification[19382]: FATAL: (4) 4       0x7f4a00ac2957 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8c957) [0x7f4a00ac2957]---------
Jun 17 18:56:33 fledge-VirtualBox Fledge Fledge notification[19382]: FATAL: (5) 5       0x7f4a00ac8ae6 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92ae6) [0x7f4a00ac8ae6]---------
Jun 17 18:56:33 fledge-VirtualBox Fledge Fledge notification[19382]: FATAL: (6) 6       0x7f4a00ac8b21 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92b21) [0x7f4a00ac8b21]---------
Jun 17 18:56:33 fledge-VirtualBox Fledge Fledge notification[19382]: FATAL: (7) 7       0x7f4a00ac8d54 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x92d54) [0x7f4a00ac8d54]---------
Jun 17 18:56:33 fledge-VirtualBox Fledge Fledge notification[19382]: FATAL: (8) 8       0x7f4a0129d16c ConfigCategory::getValue(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const + 252---------
Jun 17 18:56:33 fledge-VirtualBox Fledge Fledge notification[19382]: FATAL: (9) 9       0x7f49fc1805f1 Asset::Asset(ConfigCategory*) + 129---------
Jun 17 18:56:33 fledge-VirtualBox Fledge Fledge notification[19382]: FATAL: (10) 10      0x7f49fc186411 plugin_init + 33---------
Jun 17 18:56:33 fledge-VirtualBox Fledge Fledge notification[19382]: FATAL: (11) 11      0x55ea269be4b8 DeliveryPlugin::init(ConfigCategory const&) + 56---------
Jun 17 18:56:33 fledge-VirtualBox Fledge Fledge notification[19382]: FATAL: (12) 12      0x55ea269f5d62 NotificationManager::addDelivery(ConfigCategory const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ConfigCategory&) + 578---------
Jun 17 18:56:33 fledge-VirtualBox Fledge Fledge notification[19382]: FATAL: (13) 13      0x55ea26a0da43 NotificationService::configChildCreate(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 211---------
Jun 17 18:56:33 fledge-VirtualBox Fledge Fledge notification[19382]: FATAL: (14) 14      0x7f4a00f6536c ConfigHandler::configChildCreate(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 322---------
Jun 17 18:56:33 fledge-VirtualBox Fledge Fledge notification[19382]: FATAL: (15) 15      0x7f4a00f6b506 ManagementApi::configChildCreate(std::shared_ptr<SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > >::Response>, std::shared_ptr<SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > >::Request>) + 682---------
Jun 17 18:56:33 fledge-VirtualBox Fledge Fledge notification[19382]: FATAL: (16) 16      0x7f4a00f69d6b configChildCreateWrapper(std::shared_ptr<SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> > >::Response>, std::shared_ptr<SimpleWeb::ServerBase<boost::asio::basic_stream_socket<boost::asio::ip::tcp,
```

**Comment by pintomax** [comment]
@mshariq-nerd please check you have this fledge branch FOGL-6495 and latest notification server develop.

I do not see the crash

**Comment by mshariq-nerd** [comment]
@pintomax  I am using this fledge branch FOGL-6495 and latest notification server develop. I have created the notification instance **N1**
 ```
curl -sX POST -d '{"name":"N1","description":"N1 notification instance","rule":"Threshold","channel":"asset","notification_type":"one shot","enabled":true,"retrigger_time":"60","rule_config":{},"delivery_config":{}}'  http://localhost:8081/fledge/notification
{"result": "Notification N1 created successfully"}
```

**Comment by pintomax** [comment]
> @pintomax I am using this fledge branch FOGL-6495 and latest notification server develop. I have created the notification instance **N1**
> 
> ```
> curl -sX POST -d '{"name":"N1","description":"N1 notification instance","rule":"Threshold","channel":"asset","notification_type":"one shot","enabled":true,"retrigger_time":"60","rule_config":{},"delivery_config":{}}'  http://localhost:8081/fledge/notification
> {"result": "Notification N1 created successfully"}
> ```

I haven't understood whether you got a crash or not

**Comment by pintomax** [comment]
@mshariq-nerd 

This is my Ubuntu 18 setup

curl -sX POST http://localhost:8081/fledge/notification/N1/delivery -d '{"name": "coolant", "config": {"action": {"description": "Perform a control action to turn pump", "type": "boolean", "default": "false"}, "plugin": {"description": "asset plugin","type": "string","readonly": "true","default": "asset"}}}'

No crash

{
  "channels": [
    "deliveryN1/control",
    "coolant"
  ]
}


I see categories in the database as well
N1_channel_coolant|N1_channel_coolant|coolant delivery channel|{"action":{"description":"Perform a control action to turn pump","type":"boolean","default":"false","value":"false"},"plugin":{"description":"asset plugin","type":"string","readonly":"true","default":"telegram","value":"asset"}}

19|N1|N1_channel_coolant

**Comment by mshariq-nerd** [comment]
@pintomax  I am still getting the crash with fresh setup.

**Comment by pintomax** [comment]
@mshariq-nerd The payload passed to new delivery endpoint is the same we pass when we set the delivery channel of the notification instance:

i.e. It must contain ALL needed plugin configuration data.

These full examples work
```
curl -sX POST http://localhost:8081/foglamp/notification/N1/delivery  -d @- <<EOF
{
    "name": "BL",
    "description": "Blynk delibery",
    "config": {
          "plugin": {
            "description": "Blynk notification plugin",
            "type": "string",
            "readonly": "true",
            "default": "Blynk"
          },
          "enable": {
            "description": "A switch that can be used to enable or disable execution of the Slack notification plugin.",
            "type": "boolean",
            "displayName": "Enabled",
            "default": "true"
          },
          "api_url": {
            "description": "Blynk REST API url prefix.",
            "type": "string",
            "order": "1",
            "displayName": "Blynk API url prefix",
            "default": "http://blynk-cloud.com"
          },
          "pin": {
            "description": "The Blynk Pin for device or Virtual Pin",
            "type": "string",
            "order": "2",
            "displayName": "The Blynk Pin for device or Virtual Pin",
            "default": "http://blynk-cloud.com"
          },
	  "token": {
		"description": "The Blynk REST API token",
		"type": "string",
		"order": "3",
		"displayName": "The Blynk REST API token",
		"default": ""
	}

    }
}
EOF
```

```
curl -sX POST http://localhost:8081/fledge/notification/N1/delivery  -d @- <<EOF
{
    "name": "TLG",
    "description": "asset new delibery",
    "config": {
          "plugin": {
            "description": "Telegram notification plugin",
            "type": "string",
            "readonly": "true",
            "default": "Telegram"
          },
          "enable": {
            "description": "A switch that can be used to enable or disable execution of the Slack notification plugin.",
            "type": "boolean",
            "displayName": "Enabled",
            "default": "true"
          },
          "chat_id": {
            "description": "The chat_id of Telegram user",
            "type": "string",
            "order": "1",
            "displayName": "The chat_id of Telegram user",
            "default": ""
          },
          "api_url": {
            "description": "Telegram BOT API url prefix",
            "type": "string",
            "order": "2",
            "displayName": "Telegram BOT API url prefix",
            "default": "https://api.telegram.org/bot"
          },
	  "token": {
		"description": "The Telegram BOT API token",
		"type": "string",
		"order": "3",
		"displayName": "Telegram BOT API token",
		"default": ""
	}

    }
}
EOF
```

**Comment by mshariq-nerd** [comment]
@pintomax  syslog entries? have you seen entries in syslog while creating multiple delivery channel? Are you not getting any FATAL in syslog?

**Comment by mshariq-nerd** [comment]
>i.e. It must contain ALL needed plugin configuration data.
I have tested it with all plugin configuration data and with that NOT seeing any crash in syslog, all looks good. But yes if the payload don't have complete configuration data it is throwing fatal in syslog. IMO it is better to handle it gracefully by throwing some kind of missing configuration key value error instead of fatal.

**Comment by pintomax** [comment]
@mshariq-nerd when we create a notification N1, say with GUI, the user is asked to select rule and delivery plugin.

These actions fetch the plugin configuration (rule and delivery) and  then the notification instance is created without any issue.

We need to to the same in the GUI for additional channels: the user see a list and whatever plugin is selected is configuration is fetched and then the needed payload will be build.

Plugins do abort at plugin_init if required configuration is not available, that's why we have the get_plugin_info for C++ and python ones

**Comment by mshariq-nerd** [comment]
@pintomax, I know with GUI there will not be any issue as we fetch the config on plugin selection .  I’m just saying code must be robust and API should tell user what is the issue! Instead of fatal. 
BTW I am approving.

**Review by mshariq-nerd — APPROVED** [review]

**Pull request merged**
