### PR TITLE
FOGL-4881: new library version fixes HTTPS response

### PR DESCRIPTION
**Pull request by pintomax**
FOGL-4881: new library version fixes HTTPS response

### CODE REVIEW

**Comment by pintomax** [comment]
@YashTatkondawar I found compilation easy on Ubuntu 18 and Pi4 with Buster

On Pi3 I needed to instal a library, `libboost-filesystem-dev`, which broke my setup.


We need to verify Fledge and FogLAMP run well in all the systems

**Comment by YashTatkondawar** [comment]
> @YashTatkondawar I found compilation easy on Ubuntu 18 and Pi4 with Buster
> 
> On Pi3 I needed to instal a library, `libboost-filesystem-dev`, which broke my setup.
> 
> We need to verify Fledge and FogLAMP run well in all the systems

@pintomax Currently we have all our testing on Rpi0 and Rpi4 buster based platform as both are latest. We never had a requirement of fledge/foglamp on Rpi3 and so it is not being tested also. If it is a requirement now then I can ask Ashwin to setup a board and then we can automate tests on them. Could you let me know if your RPi3 is running buster or stretch? If it is a stretch platform, then we build packages on moxa and test it locally. Also could you please provide details of what exactly broke in your setup? @pintomax and @MarkRiddoch could you please give me the list of all systems (apart from which we currently test on) so that I can verify Fledge and FogLAMP runs well on them.

**Comment by pintomax** [comment]
@YashTatkondawar I had an issue in a Pi3 buster, which is not working today due to sdhc card issue!

In another Pi3 Buster I can compile this branch without issues, no needed libraries
Compilation succeeds in Centos 7.8

**Review by MarkRiddoch — COMMENTED** [review]
This is a very core piece of our system, I think we need to run system tests on all the supported platforms before we merge this. @YashTatkondawar can you trigger these please?

**Review by sstefano69 — DISMISSED** [review]
it solves the problems I encountered during - Fogl 4758: Pi Web API south plugin

**Review by YashTatkondawar — COMMENTED** [review]
System tests are good on all supported platforms.

**Review by YashTatkondawar — APPROVED** [review]

**Review by sstefano69 — APPROVED** [review]

**Pull request merged**
