### PR TITLE
FOGL-6945: Acquire and release GIL properly around calls to embedded Python library

### PR DESCRIPTION
**Pull request by AmandeepArora**
Reported segfault was probably because system ran out of RAM when run with default "-j4" option for make command, which was too much for a RPi with 1 GB RAM.

Signed-off-by: Amandeep Singh Arora <aman@dianomic.com>

### CODE REVIEW

**Comment by AmandeepArora** [comment]
> On Jenkins below commands are running for C-unit tests execution
> 
> ```
> export FLEDGE_ROOT=/home/pi/Fledge; $FLEDGE_ROOT/tests/unit/C/scripts/RunAllTests.sh -j1
> ```
> 
> **Raspberry Pi 4 Model B Rev 1.1**
> 
> You can see C-unit tests run with `-j1` flag.
> 
> Have you checked/ran the tests locally on bullseye?

Yes, I tried "-j1" on RPi4 with bullseye and it worked fine after this change. Failed without this change.

**Comment by AmandeepArora** [comment]
> On Jenkins below commands are running for C-unit tests execution
> 
> ```
> export FLEDGE_ROOT=/home/pi/Fledge; $FLEDGE_ROOT/tests/unit/C/scripts/RunAllTests.sh -j1
> ```
> 
> **Raspberry Pi 4 Model B Rev 1.1**
> 
> You can see C-unit tests run with `-j1` flag.
> 
> Have you checked/ran the tests locally on bullseye?

Earlier "-j1" was not getting propagated to the make command, make always ran with "-j4".

**Review by ashish-jabble — CHANGES_REQUESTED** [review]
I am still getting the segmentation fault while running C-unit tests.
```
/usr/include/c++/10/bits/stl_iterator.h:1225:5: note: parameter passing for argument of type '__gnu_cxx::__normal_iterator<const double*, std::vector<double> >' changed in GCC 7.1
 1225 |     __niter_base(__gnu_cxx::__normal_iterator<_Iterator, _Container> __it)
      |     ^~~~~~~~~~~~
/home/pi/fledge/tests/unit/C/scripts/RunAllTests.sh: line 82: 12630 Segmentation fault      ./RunTests --gtest_output=xml > /tmp/results
Tests for ./common failed
```

**Review by MarkRiddoch — APPROVED** [review]
Thanks, thanks eats now passing on my Bullseye platform. Wonder how we got away with this on other platforms.

Maybe correct PR title.

**Pull request merged**
