### PR TITLE
FOGL-5356: fledge start does not work with sqlitelb engine

### PR DESCRIPTION
**Pull request by sstefano69**
Signed-off-by: Stefano <stefano@dianomic.com>

### CODE REVIEW

**Review by YashTatkondawar — CHANGES_REQUESTED** [review]
1. Set the Storage plugin to sqlitelb at Configuration->Advanced->Storage in GUI.
2. Restart fledge.

Result: Fledge does not start.
Syslogs:
```
Apr 27 05:45:42 ip-10-0-0-53 fledge.services.storage: INFO: Storage configuration cache is up to date
Apr 27 05:45:50 ip-10-0-0-53 Fledge Storage[23822]: ERROR: Failed to attach 'readings' database in 'ATTACH DATABASE '/home/ubuntu/fledge/data/readings.db' AS readings;': error unable to open database: /home/ubuntu/fledge/data/readings.db
Apr 27 05:45:50 ip-10-0-0-53 Fledge Storage[23822]: ERROR: Failed to set WAL from the readings DB - PRAGMA busy_timeout = 5000; PRAGMA cache_size = -4000; PRAGMA journal_mode = WAL; PRAGMA secure_delete = off; PRAGMA journal_size_limit = 4096000; : error #020▒▒RPV
Apr 27 05:45:50 ip-10-0-0-53 Fledge Storage[23822]: FATAL: Signal 6 (Aborted) trapped:
Apr 27 05:45:50 ip-10-0-0-53 Fledge Storage[23822]: FATAL: (0) 0       0x565050f79c29 /home/ubuntu/fledge/services/fledge.services.storage(+0x54c29) [0x565050f79c29]---------
Apr 27 05:45:50 ip-10-0-0-53 Fledge Storage[23822]: FATAL: (1) 1       0x7f210be5b040 /lib/x86_64-linux-gnu/libc.so.6(+0x3f040) [0x7f210be5b040]---------
Apr 27 05:45:50 ip-10-0-0-53 Fledge Storage[23822]: FATAL: (2) 2       0x7f210be5afb7 gsignal + 199---------
Apr 27 05:45:50 ip-10-0-0-53 Fledge Storage[23822]: FATAL: (3) 3       0x7f210be5c921 abort + 321---------
Apr 27 05:45:50 ip-10-0-0-53 Fledge Storage[23822]: FATAL: (4) 4       0x7f210bea5967 /lib/x86_64-linux-gnu/libc.so.6(+0x89967) [0x7f210bea5967]---------
Apr 27 05:45:50 ip-10-0-0-53 Fledge Storage[23822]: FATAL: (5) 5       0x7f210beac9da /lib/x86_64-linux-gnu/libc.so.6(+0x909da) [0x7f210beac9da]---------
Apr 27 05:45:50 ip-10-0-0-53 Fledge Storage[23822]: FATAL: (6) 6       0x7f210beb420d cfree + 2013---------
Apr 27 05:45:50 ip-10-0-0-53 Fledge Storage[23822]: FATAL: (7) 7       0x7f210ab595c3 sqlite3_free + 83---------
Apr 27 05:45:50 ip-10-0-0-53 Fledge Storage[23822]: FATAL: (8) 8       0x7f210b0560c5 Connection::Connection() + 1653---------
Apr 27 05:45:50 ip-10-0-0-53 Fledge Storage[23822]: FATAL: (9) 9       0x7f210b0648ae ConnectionManager::growPool(unsigned int) + 126---------
Apr 27 05:45:50 ip-10-0-0-53 Fledge Storage[23822]: FATAL: (10) 10      0x7f210b06c3b3 plugin_init + 243---------
Apr 27 05:45:50 ip-10-0-0-53 Fledge Storage[23822]: FATAL: (11) 11      0x565050fb5a28 StoragePlugin::StoragePlugin(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*) + 3304---------
Apr 27 05:45:50 ip-10-0-0-53 Fledge Storage[23822]: FATAL: (12) 12      0x565050f7a571 StorageService::loadPlugin() + 273---------
Apr 27 05:45:50 ip-10-0-0-53 Fledge Storage[23822]: FATAL: (13) 13      0x565050f7ad04 StorageService::start(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, unsigned short) + 52---------
Apr 27 05:45:50 ip-10-0-0-53 Fledge Storage[23822]: FATAL: (14) 14      0x565050f6886d main + 749---------
Apr 27 05:45:50 ip-10-0-0-53 Fledge Storage[23822]: FATAL: (15) 15      0x7f210be3dbf7 __libc_start_main + 231---------
Apr 27 05:45:50 ip-10-0-0-53 Fledge Storage[23822]: FATAL: (16) 16      0x565050f6982a _start + 42---------
```

Note: Same result even if we change from storage.json.

**Review by pintomax — APPROVED** [review]

**Review by YashTatkondawar — CHANGES_REQUESTED** [review]
With the latest changes, we are able to switch the database to sqlitelb from GUI also.
But there is an issue in fledge reset with sqlitelb.
Steps:
1. Load some readings and stop fledge
2. Reset fledge
3. Start fledge

```
ubuntu@ip-10-0-0-53:~/fledge$ ./scripts/fledge stop
Stopping Fledge.........
Fledge stopped.
ubuntu@ip-10-0-0-53:~/fledge$ ./scripts/fledge reset
This script will remove all data stored in the SQLite3 datafiles:
'/home/ubuntu/fledge/data/fledge.db'
'/home/ubuntu/fledge/data/readings.db'
Enter YES if you want to continue: YES
ubuntu@ip-10-0-0-53:~/fledge$ ls data/
core.err  etc  extras  fledge.db  logs  plugins  readings.db  readings_1.db  readings_2.db  readings_3.db  var
ubuntu@ip-10-0-0-53:~/fledge$ ./scripts/fledge start
Starting Fledge v1.9.0.......
Fledge started.
```

The reset command is not executed properly as it is not showing "Removed user data from" logs and also db files are not removed. After reset although in GUI, the ping count is 0 but in the Assets and Readings page we can still see asset with the readings.

**Review by MarkRiddoch — APPROVED** [review]

**Comment by sstefano69** [comment]
It worked properly, please can you recheck it 
```
foglamp@ihsdev:~/Development/fledge$ git status
On branch FOGL-5356
Your branch is up to date with 'origin/FOGL-5356'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        0_links
        1_links_dev
        2_links_sys
        data/omf.log
        data/omf.txt

nothing added to commit but untracked files present (use "git add" to track)
foglamp@ihsdev:~/Development/fledge$ ./scripts/fledge stop
It looks like Fledge is not running.
foglamp@ihsdev:~/Development/fledge$ ./scripts/fledge start
Starting Fledge v1.9.0........
Fledge started.
foglamp@ihsdev:~/Development/fledge$ ll data
total 1.9M
drwxrwxr-x  6 foglamp foglamp 4.0K Apr 28 15:08 .
drwxrwxr-x 20 foglamp foglamp 4.0K Apr 23 12:47 ..
-rw-rw-r--  1 foglamp foglamp    0 Apr 28 15:08 core.err
drwxrwxr-x  4 foglamp foglamp 4.0K Apr 28 15:08 etc
drwxrwxr-x  3 foglamp foglamp 4.0K Feb 13  2020 extras
-rw-r--r--  1 foglamp foglamp 380K Apr 28 15:08 fledge.db
-rw-r--r--  1 foglamp foglamp  32K Apr 28 15:08 fledge.db-shm
-rw-r--r--  1 foglamp foglamp 355K Apr 28 15:08 fledge.db-wal
drwxrwxr-x  2 foglamp foglamp 4.0K Apr 23 08:42 logs
-rw-rw-r--  1 foglamp foglamp  26K Apr 28 15:04 omf.log
-rw-rw-r--  1 foglamp foglamp   45 Apr 28 15:02 omf.txt
-rw-r--r--  1 foglamp foglamp  24K Apr 28 15:08 readings_1.db
-rw-r--r--  1 foglamp foglamp  32K Apr 28 15:08 readings_1.db-shm
-rw-r--r--  1 foglamp foglamp 343K Apr 28 15:08 readings_1.db-wal
-rw-r--r--  1 foglamp foglamp 4.0K Apr 28 15:08 readings_2.db
-rw-r--r--  1 foglamp foglamp  32K Apr 28 15:08 readings_2.db-shm
-rw-r--r--  1 foglamp foglamp 310K Apr 28 15:08 readings_2.db-wal
-rw-r--r--  1 foglamp foglamp 4.0K Apr 28 15:08 readings_3.db
-rw-r--r--  1 foglamp foglamp  32K Apr 28 15:08 readings_3.db-shm
-rw-r--r--  1 foglamp foglamp 310K Apr 28 15:08 readings_3.db-wal
drwxrwxr-x  3 foglamp foglamp 4.0K Feb 13  2020 var
foglamp@ihsdev:~/Development/fledge$ ./scripts/fledge stop
Stopping Fledge....
Fledge stopped.
foglamp@ihsdev:~/Development/fledge$ ./scripts/fledge reset
This script will remove all data stored in the SQLite3 datafiles:
'/home/foglamp/Development/fledge/data/fledge.db'
'/home/foglamp/Development/fledge/data/readings_1.db'
Enter YES if you want to continue: YES
Removed user data from /home/foglamp/Development/fledge/data/scripts
Removed user data from /home/foglamp/Development/fledge/data/logs
Removed user data from /home/foglamp/Development/fledge/data/var
Removed user data from /home/foglamp/Development/fledge/data/extras
Removed user data from /home/foglamp/Development/fledge/data/etc
Removed core.err from /home/foglamp/Development/fledge/data
Removed user data from /home/foglamp/Development/fledge/data/snapshots
Removed user data from /home/foglamp/Development/fledge/data/backup
Removed user data from /home/foglamp/Development/fledge/data/support
Removed user CSV files from /home/foglamp/Development/fledge/data
foglamp@ihsdev:~/Development/fledge$ ll data
total 464K
drwxrwxr-x  6 foglamp foglamp 4.0K Apr 28 15:09 .
drwxrwxr-x 20 foglamp foglamp 4.0K Apr 23 12:47 ..
drwxrwxr-x  4 foglamp foglamp 4.0K Apr 28 15:09 etc
drwxrwxr-x  3 foglamp foglamp 4.0K Feb 13  2020 extras
-rw-r--r--  1 foglamp foglamp 380K Apr 28 15:09 fledge.db
drwxrwxr-x  2 foglamp foglamp 4.0K Apr 23 08:42 logs
-rw-rw-r--  1 foglamp foglamp  26K Apr 28 15:04 omf.log
-rw-rw-r--  1 foglamp foglamp   45 Apr 28 15:02 omf.txt
-rw-r--r--  1 foglamp foglamp  24K Apr 28 15:09 readings_1.db
drwxrwxr-x  3 foglamp foglamp 4.0K Feb 13  2020 var
foglamp@ihsdev:~/Development/fledge$ ./scripts/fledge start
Starting Fledge v1.9.0........
Fledge started.
foglamp@ihsdev:~/Development/fledge$ ll data
total 1.9M
drwxrwxr-x  6 foglamp foglamp 4.0K Apr 28 15:09 .
drwxrwxr-x 20 foglamp foglamp 4.0K Apr 23 12:47 ..
-rw-rw-r--  1 foglamp foglamp    0 Apr 28 15:09 core.err
drwxrwxr-x  4 foglamp foglamp 4.0K Apr 28 15:09 etc
drwxrwxr-x  3 foglamp foglamp 4.0K Feb 13  2020 extras
-rw-r--r--  1 foglamp foglamp 380K Apr 28 15:09 fledge.db
-rw-r--r--  1 foglamp foglamp  32K Apr 28 15:09 fledge.db-shm
-rw-r--r--  1 foglamp foglamp 355K Apr 28 15:09 fledge.db-wal
drwxrwxr-x  2 foglamp foglamp 4.0K Apr 23 08:42 logs
-rw-rw-r--  1 foglamp foglamp  26K Apr 28 15:04 omf.log
-rw-rw-r--  1 foglamp foglamp   45 Apr 28 15:02 omf.txt
-rw-r--r--  1 foglamp foglamp  24K Apr 28 15:09 readings_1.db
-rw-r--r--  1 foglamp foglamp  32K Apr 28 15:09 readings_1.db-shm
-rw-r--r--  1 foglamp foglamp 343K Apr 28 15:09 readings_1.db-wal
-rw-r--r--  1 foglamp foglamp 4.0K Apr 28 15:09 readings_2.db
-rw-r--r--  1 foglamp foglamp  32K Apr 28 15:09 readings_2.db-shm
-rw-r--r--  1 foglamp foglamp 310K Apr 28 15:09 readings_2.db-wal
-rw-r--r--  1 foglamp foglamp 4.0K Apr 28 15:09 readings_3.db
-rw-r--r--  1 foglamp foglamp  32K Apr 28 15:09 readings_3.db-shm
-rw-r--r--  1 foglamp foglamp 310K Apr 28 15:09 readings_3.db-wal
drwxrwxr-x  3 foglamp foglamp 4.0K Feb 13  2020 var

```

**Comment by YashTatkondawar** [comment]
> @YashTatkondawar - It worked properly, please can you recheck it
> 
> ```
> foglamp@ihsdev:~/Development/fledge$ git status
> On branch FOGL-5356
> Your branch is up to date with 'origin/FOGL-5356'.
> 
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 
>         0_links
>         1_links_dev
>         2_links_sys
>         data/omf.log
>         data/omf.txt
> 
> nothing added to commit but untracked files present (use "git add" to track)
> foglamp@ihsdev:~/Development/fledge$ ./scripts/fledge stop
> It looks like Fledge is not running.
> foglamp@ihsdev:~/Development/fledge$ ./scripts/fledge start
> Starting Fledge v1.9.0........
> Fledge started.
> foglamp@ihsdev:~/Development/fledge$ ll data
> total 1.9M
> drwxrwxr-x  6 foglamp foglamp 4.0K Apr 28 15:08 .
> drwxrwxr-x 20 foglamp foglamp 4.0K Apr 23 12:47 ..
> -rw-rw-r--  1 foglamp foglamp    0 Apr 28 15:08 core.err
> drwxrwxr-x  4 foglamp foglamp 4.0K Apr 28 15:08 etc
> drwxrwxr-x  3 foglamp foglamp 4.0K Feb 13  2020 extras
> -rw-r--r--  1 foglamp foglamp 380K Apr 28 15:08 fledge.db
> -rw-r--r--  1 foglamp foglamp  32K Apr 28 15:08 fledge.db-shm
> -rw-r--r--  1 foglamp foglamp 355K Apr 28 15:08 fledge.db-wal
> drwxrwxr-x  2 foglamp foglamp 4.0K Apr 23 08:42 logs
> -rw-rw-r--  1 foglamp foglamp  26K Apr 28 15:04 omf.log
> -rw-rw-r--  1 foglamp foglamp   45 Apr 28 15:02 omf.txt
> -rw-r--r--  1 foglamp foglamp  24K Apr 28 15:08 readings_1.db
> -rw-r--r--  1 foglamp foglamp  32K Apr 28 15:08 readings_1.db-shm
> -rw-r--r--  1 foglamp foglamp 343K Apr 28 15:08 readings_1.db-wal
> -rw-r--r--  1 foglamp foglamp 4.0K Apr 28 15:08 readings_2.db
> -rw-r--r--  1 foglamp foglamp  32K Apr 28 15:08 readings_2.db-shm
> -rw-r--r--  1 foglamp foglamp 310K Apr 28 15:08 readings_2.db-wal
> -rw-r--r--  1 foglamp foglamp 4.0K Apr 28 15:08 readings_3.db
> -rw-r--r--  1 foglamp foglamp  32K Apr 28 15:08 readings_3.db-shm
> -rw-r--r--  1 foglamp foglamp 310K Apr 28 15:08 readings_3.db-wal
> drwxrwxr-x  3 foglamp foglamp 4.0K Feb 13  2020 var
> foglamp@ihsdev:~/Development/fledge$ ./scripts/fledge stop
> Stopping Fledge....
> Fledge stopped.
> foglamp@ihsdev:~/Development/fledge$ ./scripts/fledge reset
> This script will remove all data stored in the SQLite3 datafiles:
> '/home/foglamp/Development/fledge/data/fledge.db'
> '/home/foglamp/Development/fledge/data/readings_1.db'
> Enter YES if you want to continue: YES
> Removed user data from /home/foglamp/Development/fledge/data/scripts
> Removed user data from /home/foglamp/Development/fledge/data/logs
> Removed user data from /home/foglamp/Development/fledge/data/var
> Removed user data from /home/foglamp/Development/fledge/data/extras
> Removed user data from /home/foglamp/Development/fledge/data/etc
> Removed core.err from /home/foglamp/Development/fledge/data
> Removed user data from /home/foglamp/Development/fledge/data/snapshots
> Removed user data from /home/foglamp/Development/fledge/data/backup
> Removed user data from /home/foglamp/Development/fledge/data/support
> Removed user CSV files from /home/foglamp/Development/fledge/data
> foglamp@ihsdev:~/Development/fledge$ ll data
> total 464K
> drwxrwxr-x  6 foglamp foglamp 4.0K Apr 28 15:09 .
> drwxrwxr-x 20 foglamp foglamp 4.0K Apr 23 12:47 ..
> drwxrwxr-x  4 foglamp foglamp 4.0K Apr 28 15:09 etc
> drwxrwxr-x  3 foglamp foglamp 4.0K Feb 13  2020 extras
> -rw-r--r--  1 foglamp foglamp 380K Apr 28 15:09 fledge.db
> drwxrwxr-x  2 foglamp foglamp 4.0K Apr 23 08:42 logs
> -rw-rw-r--  1 foglamp foglamp  26K Apr 28 15:04 omf.log
> -rw-rw-r--  1 foglamp foglamp   45 Apr 28 15:02 omf.txt
> -rw-r--r--  1 foglamp foglamp  24K Apr 28 15:09 readings_1.db
> drwxrwxr-x  3 foglamp foglamp 4.0K Feb 13  2020 var
> foglamp@ihsdev:~/Development/fledge$ ./scripts/fledge start
> Starting Fledge v1.9.0........
> Fledge started.
> foglamp@ihsdev:~/Development/fledge$ ll data
> total 1.9M
> drwxrwxr-x  6 foglamp foglamp 4.0K Apr 28 15:09 .
> drwxrwxr-x 20 foglamp foglamp 4.0K Apr 23 12:47 ..
> -rw-rw-r--  1 foglamp foglamp    0 Apr 28 15:09 core.err
> drwxrwxr-x  4 foglamp foglamp 4.0K Apr 28 15:09 etc
> drwxrwxr-x  3 foglamp foglamp 4.0K Feb 13  2020 extras
> -rw-r--r--  1 foglamp foglamp 380K Apr 28 15:09 fledge.db
> -rw-r--r--  1 foglamp foglamp  32K Apr 28 15:09 fledge.db-shm
> -rw-r--r--  1 foglamp foglamp 355K Apr 28 15:09 fledge.db-wal
> drwxrwxr-x  2 foglamp foglamp 4.0K Apr 23 08:42 logs
> -rw-rw-r--  1 foglamp foglamp  26K Apr 28 15:04 omf.log
> -rw-rw-r--  1 foglamp foglamp   45 Apr 28 15:02 omf.txt
> -rw-r--r--  1 foglamp foglamp  24K Apr 28 15:09 readings_1.db
> -rw-r--r--  1 foglamp foglamp  32K Apr 28 15:09 readings_1.db-shm
> -rw-r--r--  1 foglamp foglamp 343K Apr 28 15:09 readings_1.db-wal
> -rw-r--r--  1 foglamp foglamp 4.0K Apr 28 15:09 readings_2.db
> -rw-r--r--  1 foglamp foglamp  32K Apr 28 15:09 readings_2.db-shm
> -rw-r--r--  1 foglamp foglamp 310K Apr 28 15:09 readings_2.db-wal
> -rw-r--r--  1 foglamp foglamp 4.0K Apr 28 15:09 readings_3.db
> -rw-r--r--  1 foglamp foglamp  32K Apr 28 15:09 readings_3.db-shm
> -rw-r--r--  1 foglamp foglamp 310K Apr 28 15:09 readings_3.db-wal
> drwxrwxr-x  3 foglamp foglamp 4.0K Feb 13  2020 var
> ```

@sstefano69 I have reverified and I am still seeing the issue. I hope you have verified with sqlitelb plugin.

**Review by pintomax — APPROVED** [review]

**Review by YashTatkondawar — APPROVED** [review]
lgtm with the latest changes.

**Pull request merged**
