### PR TITLE
FOGL-8944 Alter branch completion criteria to allow for filter plugin…

### PR DESCRIPTION
**Pull request by MarkRiddoch**
…s that do

not forward data always and simply return

### CODE REVIEW

**Review by AmandeepArora — APPROVED** [review]

**Comment by AmandeepArora** [comment]
@MarkRiddoch: There is another case that I wanted to cross-check with you: foglamp-filter-changedetection filter can generate some readings at shutdown time also, trying to persist its in-memory information (potentially via a downstream csv-writer filter instance). Will that case work with these recent changes?

Please see here: https://github.com/dianomic/foglamp-filter-changedetection/blob/d1535b1aa756cabd973c16a3f63e2a8e7906efe0/python/foglamp/plugins/filter/changedetection/changedetection.py#L238

**Comment by MarkRiddoch** [comment]
> @MarkRiddoch: There is another case that I wanted to cross-check with you: foglamp-filter-changedetection filter can generate some readings at shutdown time also, trying to persist its in-memory information (potentially via a downstream csv-writer filter instance). Will that case work with these recent changes?
> 
> Please see here: https://github.com/dianomic/foglamp-filter-changedetection/blob/d1535b1aa756cabd973c16a3f63e2a8e7906efe0/python/foglamp/plugins/filter/changedetection/changedetection.py#L238

Hi @AmandeepArora not really sure, I'll need to look into it. I don't recall that the filter had this ability, at least not by design as they are essentially synchronous. Python had a callback mechanism, but was meant to be per invocation of the ingest call rather than for the lifetime of the pipeline. I will look into this separately.

**Comment by AmandeepArora** [comment]
> > @MarkRiddoch: There is another case that I wanted to cross-check with you: foglamp-filter-changedetection filter can generate some readings at shutdown time also, trying to persist its in-memory information (potentially via a downstream csv-writer filter instance). Will that case work with these recent changes?
> > Please see here: https://github.com/dianomic/foglamp-filter-changedetection/blob/d1535b1aa756cabd973c16a3f63e2a8e7906efe0/python/foglamp/plugins/filter/changedetection/changedetection.py#L238
> 
> Hi @AmandeepArora not really sure, I'll need to look into it. I don't recall that the filter had this ability, at least not by design as they are essentially synchronous. Python had a callback mechanism, but was meant to be per invocation of the ingest call rather than for the lifetime of the pipeline. I will look into this separately.

@MarkRiddoch : Ok sure, thanks.

**Comment by Mohit04tomar** [comment]
@MarkRiddoch @AmandeepArora I did testing of change-detection filter with the changes of this pull request and found FATAL error in syslog, for which I logged the JIRA FOGL-9027:
```
Aug 14 17:20:51 nerd-Latitude-3420 FogLAMP m1[48344]: FATAL: Signal 11 (Segmentation fault) trapped:
Aug 14 17:20:51 nerd-Latitude-3420 FogLAMP m1[48344]: FATAL: (0) 0       0x555d98abbdd2 handler(int) + 82---------
Aug 14 17:20:51 nerd-Latitude-3420 FogLAMP m1[48344]: FATAL: (1) 1       0x7f33b627e090 /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7f33b627e090]---------
Aug 14 17:20:51 nerd-Latitude-3420 FogLAMP m1[48344]: FATAL: (2) 2       0x555d98aab758 Ingest::useFilteredData(void*, ReadingSet*) + 72---------
Aug 14 17:20:51 nerd-Latitude-3420 FogLAMP m1[48344]: FATAL: (3) 3       0x7f33b6c3a7f5 /usr/local/foglamp/python/filter_ingest.so(+0x17f5) [0x7f33b6c3a7f5]---------
Aug 14 17:20:51 nerd-Latitude-3420 FogLAMP m1[48344]: FATAL: (4) 4       0x7f33b5f8d697 /lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x2a8697) [0x7f33b5f8d697]---------
Aug 14 17:20:51 nerd-Latitude-3420 FogLAMP m1[48344]: FATAL: (5) 5       0x7f33b5f8db2b _PyObject_MakeTpCall + 171---------
Aug 14 17:20:51 nerd-Latitude-3420 FogLAMP m1[48344]: FATAL: (6) 6       0x7f33b5d59df3 /lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x74df3) [0x7f33b5d59df3]---------
Aug 14 17:20:51 nerd-Latitude-3420 FogLAMP m1[48344]: FATAL: (7) 7       0x7f33b5d61ef6 _PyEval_EvalFrameDefault + 32134---------
Aug 14 17:20:51 nerd-Latitude-3420 FogLAMP m1[48344]: FATAL: (8) 8       0x7f33b5d6506b /lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x8006b) [0x7f33b5d6506b]---------
Aug 14 17:20:51 nerd-Latitude-3420 FogLAMP m1[48344]: FATAL: (9) 9       0x7f33b5f8df23 /lib/x86_64-linux-gnu/libpython3.8.so.1.0(+0x2a8f23) [0x7f33b5f8df23]---------
Aug 14 17:20:51 nerd-Latitude-3420 FogLAMP m1[48344]: FATAL: (10) 10      0x7f33b5f8f18f PyObject_CallFunction + 159---------
Aug 14 17:20:51 nerd-Latitude-3420 FogLAMP m1[48344]: FATAL: (11) 11      0x7f33b42e23a4 /usr/local/foglamp/lib/libfilter-plugin-python-interface.so(+0xd3a4) [0x7f33b42e23a4]---------
Aug 14 17:20:51 nerd-Latitude-3420 FogLAMP m1[48344]: FATAL: (12) 12      0x7f33b6ba1bf8 PipelineFilter::shutdown(ServiceHandler*, ConfigHandler*) + 728---------
Aug 14 17:20:51 nerd-Latitude-3420 FogLAMP m1[48344]: FATAL: (13) 13      0x7f33b6b6c17e FilterPipeline::cleanupFilters(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 62---------
Aug 14 17:20:51 nerd-Latitude-3420 FogLAMP m1[48344]: FATAL: (14) 14      0x555d98ab5579 Ingest::~Ingest() + 105---------
Aug 14 17:20:51 nerd-Latitude-3420 FogLAMP m1[48344]: FATAL: (15) 15      0x555d98ac317a SouthService::start(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, unsigned short) + 2250---------
Aug 14 17:20:51 nerd-Latitude-3420 FogLAMP m1[48344]: FATAL: (16) 16      0x555d98aaaa47 main + 631---------
Aug 14 17:20:51 nerd-Latitude-3420 FogLAMP m1[48344]: FATAL: (17) 17      0x7f33b625f083 __libc_start_main + 243---------
Aug 14 17:20:51 nerd-Latitude-3420 FogLAMP m1[48344]: FATAL: (18) 18      0x555d98aab58e _start + 46---------
Aug 14 17:21:02 nerd-Latitude-3420 kernel: [14506.724502] ish-hid {33AECD58-B679-4E54-9BD9-A04D34F0C226}: [hid-ish]: enum_devices_done OK, num_hid_devices=1

```

**Comment by MarkRiddoch** [comment]
> Aug 14 17:20:51 nerd-Latitude-3420 FogLAMP m1[48344]: FATAL: (2) 2       0x555d98aab758 Ingest::useFilteredData(void*, ReadingSet*) + 72---------

This is almost certainly a problem created by that plugin. It is sending data in shutdown. Which may or may not work because we collapse the pile in reverse order. We got away with it in the past if it was the last filter in the chain, but now there is always something after it which has been destroyed and now we are trying to send data to it.

@AmandeepArora This answers your question about sending data in shutdown, no, it doesn't work. We might be able to if we shutdown the pipeline the other way around, rather than in reverse. I don;t recall we we choose to use that shutdown order, but we always have.

@Mohit04tomar this crash is nothing do with this particular pull request, since we already have a Jira about this I suggest we use a different plugin to test with and handle the problem in this plugin under its own Jira as this is holding stuff up that needs to be fixed in develop for a number of other cases.

**Comment by MarkRiddoch** [comment]
FOGL-9027 address the issue with the use of the changedetection plugin

**Pull request merged**
