### PR TITLE
FOGL-4844 North service fails to correctly unregister on shutdown

### PR DESCRIPTION
**Pull request by MarkRiddoch**

### CODE REVIEW

**Review by pintomax — APPROVED** [review]

**Review by ashish-jabble — CHANGES_REQUESTED** [review]
@MarkRiddoch 
FOGL-4822 - 
1) Add north service
2) Disable north service

```
Feb  1 14:51:35 aj-ThinkPad-E450 Fledge[26280] INFO: scheduler: fledge.services.core.scheduler.scheduler: Scheduled task for schedule 'NS-1' to start at 2021-02-01 14:51:35.918764
Feb  1 14:51:35 aj-ThinkPad-E450 Fledge[26280] INFO: scheduler: fledge.services.core.scheduler.scheduler: Enabled Schedule 'NS-1/ed234723-dea3-4b85-8416-f803276f70eb' process 'north_C'
Feb  1 14:51:35 aj-ThinkPad-E450 Fledge[26280] INFO: scheduler: fledge.services.core.scheduler.scheduler: Process started: Schedule 'NS-1' process 'north_C' task 16e60630-a9d6-442c-9d7d-07d062c7cf93 pid 26741, 1 running tasks#012['services/north_C', '--port=33423', '--address=127.0.0.1', '--name=NS-1']
Feb  1 14:51:37 aj-ThinkPad-E450 Fledge[26280] INFO: service_registry: fledge.services.core.service_registry.service_registry: Registered service instance id=c9ccc5b3-4110-400f-acee-570ee6fa1337: <NS-1, type=Northbound, protocol=http, address=localhost, service port=None, management port=39303, status=1>
Feb  1 14:52:06 aj-ThinkPad-E450 Fledge[26280] INFO: utils: fledge.services.common.utils: Ping received for Service NS-1 id c9ccc5b3-4110-400f-acee-570ee6fa1337 at url http://localhost:39303/fledge/service/ping
Feb  1 14:52:06 aj-ThinkPad-E450 Fledge[26280] INFO: utils: fledge.services.common.utils: Shutting down the Northbound service NS-1 ...
Feb  1 14:52:06 aj-ThinkPad-E450 Fledge[26280] INFO: utils: fledge.services.common.utils: Service NS-1, id c9ccc5b3-4110-400f-acee-570ee6fa1337 at url http://localhost:39303/fledge/service/shutdown successfully shutdown
Feb  1 14:52:06 aj-ThinkPad-E450 Fledge[26280] INFO: scheduler: fledge.services.core.scheduler.scheduler: Disabled Schedule 'NS-1/ed234723-dea3-4b85-8416-f803276f70eb' process 'north_C'
```

Now service is not completely shutdown, records & process still there

```
$ ./scripts/fledge status
Fledge v1.8.2 running.
Fledge Uptime:  105 seconds.
Fledge records: 0 read, 0 sent, 0 purged.
Fledge does not require authentication.
=== Fledge services:
fledge.services.core
fledge.services.storage --address=0.0.0.0 --port=33423
fledge.services.north --port=33423 --address=127.0.0.1 --name=NS-1 
=== Fledge tasks:


// 20210201145217
// http://localhost:8081/fledge/service

{
  "services": [
    {
      "name": "Fledge Storage",
      "type": "Storage",
      "address": "localhost",
      "management_port": 43815,
      "service_port": 33521,
      "protocol": "http",
      "status": "running"
    },
    {
      "name": "Fledge Core",
      "type": "Core",
      "address": "0.0.0.0",
      "management_port": 33423,
      "service_port": 8081,
      "protocol": "http",
      "status": "running"
    },
    {
      "name": "NS-1",
      "type": "Northbound",
      "address": "localhost",
      "management_port": 39303,
      "service_port": null,
      "protocol": "http",
      "status": "running"
    }
  ]
}
```

And for FOGL-4844
```
Interest registry records are still there (On deleting the service | or with disabling the schedule)
```
As both are inter-related to each other.

**Comment by MarkRiddoch** [comment]
@ashish-jabble Which plugin are you using here? I'm not able to reproduce using the OPCUA north or HTTPC north, so it may be related to the plugin itself.

**Comment by ashish-jabble** [comment]
HTTP-c and in built OMF.

**Comment by MarkRiddoch** [comment]
> HTTP-c and in built OMF.

Hm, there is something odd happening here. Could you please try again for me and this time turn up the logging level to debug and let me have the output for the north service.
Thanks

**Comment by ashish-jabble** [comment]
After debug added in its advancedconfig - I don't see any debug statements on disabling schedule or shutdown service.
Issue still persists (make clean && make)

**Environment** - **ub1804**

**Syslogs**

> Feb  1 19:16:11 aj-ThinkPad-E450 Fledge[8234] INFO: scheduler: fledge.services.core.scheduler.scheduler: Scheduled task for schedule 'HTC' to start at 2021-02-01 19:16:11.862234
Feb  1 19:16:11 aj-ThinkPad-E450 Fledge[8234] INFO: scheduler: fledge.services.core.scheduler.scheduler: Enabled Schedule 'HTC/8764bb4d-4306-4daa-b064-39ff7a365d9c' process 'north_C'
Feb  1 19:16:11 aj-ThinkPad-E450 Fledge[8234] INFO: scheduler: fledge.services.core.scheduler.scheduler: Process started: Schedule 'HTC' process 'north_C' task cd734ada-b1f3-4bf1-a73d-f714b073d66d pid 9330, 2 running tasks#012['services/north_C', '--port=42503', '--address=127.0.0.1', '--name=HTC']
Feb  1 19:16:13 aj-ThinkPad-E450 Fledge[8234] INFO: service_registry: fledge.services.core.service_registry.service_registry: Registered service instance id=fb145f25-274d-4c58-8396-487c25aaac68: <HTC, type=Northbound, protocol=http, address=localhost, service port=None, management port=41449, status=1>
Feb  1 19:17:44 aj-ThinkPad-E450 Fledge[8234] INFO: utils: fledge.services.common.utils: Ping received for Service HTC id fb145f25-274d-4c58-8396-487c25aaac68 at url http://localhost:41449/fledge/service/ping
Feb  1 19:17:44 aj-ThinkPad-E450 Fledge[8234] INFO: utils: fledge.services.common.utils: Shutting down the Northbound service HTC ...
Feb  1 19:17:44 aj-ThinkPad-E450 Fledge[8234] INFO: utils: fledge.services.common.utils: Service HTC, id fb145f25-274d-4c58-8396-487c25aaac68 at url http://localhost:41449/fledge/service/shutdown successfully shutdown
Feb  1 19:17:44 aj-ThinkPad-E450 Fledge[8234] INFO: scheduler: fledge.services.core.scheduler.scheduler: Disabled Schedule 'HTC/8764bb4d-4306-4daa-b064-39ff7a365d9c' process 'north_C'


```
// 20210201190358
// http://localhost:8081/fledge/category/HTC

{
  "plugin": {
    "description": "HTTP North C Plugin, support primary and secondary destinations with failover",
    "type": "string",
    "readonly": "true",
    "default": "httpc",
    "value": "httpc"
  },
  "URL": {
    "description": "The URL of the HTTP Connector to send data to",
    "type": "string",
    "order": "1",
    "displayName": "URL",
    "default": "http://localhost:6683/sensor-reading",
    "value": "http://localhost:6683/sensor-reading"
  },
  "URL2": {
    "description": "The URL of the HTTP Connector to send data to if the primary is unavailable, if empty there is no secondary",
    "type": "string",
    "order": "1",
    "displayName": "Secondary URL",
    "default": "",
    "value": ""
  },
  "source": {
    "description": "Defines the source of the data to be sent on the stream, this may be one of either readings, statistics or audit.",
    "type": "enumeration",
    "order": "2",
    "displayName": "Source",
    "options": [
      "readings",
      "statistics"
    ],
    "default": "readings",
    "value": "readings"
  },
  "retrySleepTime": {
    "description": "Seconds between each retry for the communication, NOTE : the time is doubled at each attempt.",
    "type": "integer",
    "order": "9",
    "displayName": "Sleep Time Retry",
    "default": "1",
    "value": "1"
  },
  "maxRetry": {
    "description": "Max number of retries for the communication",
    "type": "integer",
    "order": "10",
    "displayName": "Maximum Retry",
    "default": "3",
    "value": "3"
  },
  "HttpTimeout": {
    "description": "Timeout in seconds for the HTTP operations with the HTTP Connector Relay",
    "type": "integer",
    "order": "13",
    "displayName": "Http Timeout (in seconds)",
    "default": "10",
    "value": "10"
  },
  "verifySSL": {
    "description": "Verify SSL certificate",
    "type": "boolean",
    "order": "14",
    "displayName": "Verify SSL",
    "default": "false",
    "value": "false"
  },
  "applyFilter": {
    "description": "Whether to apply filter before processing the data",
    "type": "boolean",
    "order": "15",
    "displayName": "Apply Filter",
    "default": "false",
    "value": "false"
  },
  "filterRule": {
    "description": "JQ formatted filter to apply (applicable if applyFilter is True)",
    "type": "string",
    "order": "16",
    "displayName": "Filter Rule",
    "default": ".[]",
    "value": ".[]"
  },
  "enable": {
    "description": "A switch that can be used to enable or disable execution of the sending process.",
    "type": "boolean",
    "readonly": "true",
    "default": "true",
    "value": "true"
  },
  "streamId": {
    "description": "Identifies the specific stream to handle and the related information, among them the ID of the last object streamed.",
    "type": "integer",
    "readonly": "true",
    "default": "0",
    "value": "2"
  }
}


// http://localhost:8081/fledge/category/HTCAdvanced

{
  "description": "Minimum logging level reported",
  "type": "enumeration",
  "displayName": "Minimum Log Level",
  "options": [
    "error",
    "warning",
    "info",
    "debug"
  ],
  "default": "warning",
  "value": "debug"
}
```

**Comment by MarkRiddoch** [comment]
Thanks @ashish-jabble This makes no sense whatsoever as there is no logging from your HTC service at all. on my FOGL-4844 branch I see the following
```
foglamp@foglamp-18:~/fledge$ tail -40 /var/log/syslog|grep HTC
Feb  1 14:28:54 foglamp-18 Fledge HTC[11979]: DEBUG: DataLoad received read request for 100 readings
Feb  1 14:28:54 foglamp-18 Fledge HTC[11979]: DEBUG: Fetch 100 readings from 1852842
Feb  1 14:28:54 foglamp-18 Fledge HTC[11979]: DEBUG: Buffered 100 readings for north processing
Feb  1 14:28:56 foglamp-18 Fledge[11376] INFO: utils: fledge.services.common.utils: Ping received for Service HTC id dd45ca4d-37e8-4f4b-bb52-7542aa1825c3 at url http://localhost:45029/fledge/service/ping
Feb  1 14:28:56 foglamp-18 Fledge[11376] INFO: utils: fledge.services.common.utils: Shutting down the Northbound service HTC ...
Feb  1 14:28:56 foglamp-18 Fledge HTC[11979]: INFO: North service shutdown in progress.
Feb  1 14:28:56 foglamp-18 Fledge HTC[11979]: DEBUG: North main thread woken up, shutdown true
Feb  1 14:28:56 foglamp-18 Fledge HTC[11979]: DEBUG: North service is shutting down
Feb  1 14:28:56 foglamp-18 Fledge HTC[11979]: INFO: DataSender shutdown in progress
Feb  1 14:28:56 foglamp-18 Fledge[11376] INFO: utils: fledge.services.common.utils: Service HTC, id dd45ca4d-37e8-4f4b-bb52-7542aa1825c3 at url http://localhost:45029/fledge/service/shutdown successfully shutdown
Feb  1 14:28:56 foglamp-18 Fledge[11376] INFO: scheduler: fledge.services.core.scheduler.scheduler: Disabled Schedule 'HT/7d02e440-3500-463e-8540-73bb16b1f716' process 'north_C'
Feb  1 14:28:57 foglamp-18 Fledge HTC[11979]: ERROR: http-north C plugin: Sending JSON data exception: Failed to send data: Connection refused
Feb  1 14:28:57 foglamp-18 Fledge HTC[11979]: INFO: Sending thread shutdown
Feb  1 14:28:57 foglamp-18 Fledge HTC[11979]: INFO: DataSender shutdown complete
Feb  1 14:28:57 foglamp-18 Fledge HTC[11979]: INFO: Data load shutdown in progress
Feb  1 14:28:57 foglamp-18 Fledge HTC[11979]: DEBUG: DataLoad received read request for 0 readings
Feb  1 14:28:57 foglamp-18 Fledge HTC[11979]: DEBUG: Fetch 0 readings from 1852942
Feb  1 14:28:57 foglamp-18 Fledge HTC[11979]: DEBUG: No readings available
Feb  1 14:28:57 foglamp-18 Fledge HTC[11979]: INFO: Data load shutdown complete
foglamp@foglamp-18:~/fledge$ 
```

I would have at lest expected to see something relating to attempts to send data. Could you just check to see if your branch is up to date? Do you have any data to send?

**Comment by ashish-jabble** [comment]
> Could you just check to see if your branch is up to date? Do you have any data to send?


1. Reset-DB
2. git pull your branch
3. make clean && make -j4
4. Fledge start
5. Add Randomwalk south service (Ingest is okay)
6. Add North Service

At step 6 - I don't have any http server is running on machine (http://localhost:6683/sensor-reading) - On disabling schedule; service is still running

**Second scenario:** Repeat above steps but this time http server running on same port 6683 (Able to see Egress | Sent readings)
On disable its schedule, now service goes unresponsive & then failed

```
Feb  1 20:08:52 aj-ThinkPad-E450 Fledge[28176] INFO: scheduler: fledge.services.core.scheduler.scheduler: Scheduled task for schedule 'HTC' to start at 2021-02-01 20:08:52.543315
Feb  1 20:08:52 aj-ThinkPad-E450 Fledge[28176] INFO: scheduler: fledge.services.core.scheduler.scheduler: Enabled Schedule 'HTC/420a678b-527f-4cb1-93b0-b264db256fa8' process 'north_C'
Feb  1 20:08:52 aj-ThinkPad-E450 Fledge[28176] INFO: scheduler: fledge.services.core.scheduler.scheduler: Process started: Schedule 'HTC' process 'north_C' task d0c9a677-ccd0-4d39-a414-9abcac586522 pid 28751, 2 running tasks#012['services/north_C', '--port=41137', '--address=127.0.0.1', '--name=HTC']
Feb  1 20:08:53 aj-ThinkPad-E450 Fledge[28176] INFO: service_registry: fledge.services.core.service_registry.service_registry: Registered service instance id=73544098-b75a-4fe2-8fa1-5886a5c31d7b: <HTC, type=Northbound, protocol=http, address=localhost, service port=None, management port=38103, status=1>
Feb  1 20:09:29 aj-ThinkPad-E450 Fledge[28176] INFO: utils: fledge.services.common.utils: Ping received for Service HTC id 73544098-b75a-4fe2-8fa1-5886a5c31d7b at url http://localhost:38103/fledge/service/ping
Feb  1 20:09:29 aj-ThinkPad-E450 Fledge[28176] INFO: utils: fledge.services.common.utils: Shutting down the Northbound service HTC ...
Feb  1 20:09:29 aj-ThinkPad-E450 Fledge[28176] INFO: utils: fledge.services.common.utils: Service HTC, id 73544098-b75a-4fe2-8fa1-5886a5c31d7b at url http://localhost:38103/fledge/service/shutdown successfully shutdown
Feb  1 20:09:29 aj-ThinkPad-E450 Fledge[28176] INFO: scheduler: fledge.services.core.scheduler.scheduler: Disabled Schedule 'HTC/420a678b-527f-4cb1-93b0-b264db256fa8' process 'north_C'
Feb  1 20:10:43 aj-ThinkPad-E450 Fledge[28176] INFO: service_registry: fledge.services.core.service_registry.service_registry: Mark as failed service instance id=73544098-b75a-4fe2-8fa1-5886a5c31d7b: <HTC, type=Northbound, protocol=http, address=localhost, service port=None, management port=38103, status=3>
Feb  1 20:10:43 aj-ThinkPad-E450 Fledge[28176] INFO: scheduler: fledge.services.core.scheduler.scheduler: Service HTC records successfully removed
Feb  1 20:10:48 aj-ThinkPad-E450 Fledge[28176] INFO: scheduler: fledge.services.core.scheduler.scheduler: Schedule 'HTC' is not enabled
Feb  1 20:11:28 aj-ThinkPad-E450 Fledge[28176] message repeated 8 times: [ INFO: scheduler: fledge.services.core.scheduler.scheduler: Schedule 'HTC' is not enabled]
Feb  1 20:11:33 aj-ThinkPad-E450 Fledge[28176] INFO: scheduler: fledge.services.core.scheduler.scheduler: Schedule 'HTC' is not enabled
Feb  1 20:12:13 aj-ThinkPad-E450 Fledge[28176] message repeated 8 times: [ INFO: scheduler: fledge.services.core.scheduler.scheduler: Schedule 'HTC' is not enabled]
Feb  1 20:12:18 aj-ThinkPad-E450 Fledge[28176] INFO: scheduler: fledge.services.core.scheduler.scheduler: Schedule 'HTC' is not enabled
Feb  1 20:14:58 aj-ThinkPad-E450 Fledge[28176] message repeated 32 times: [ INFO: scheduler: fledge.services.core.scheduler.scheduler: Schedule 'HTC' is not enabled]
Feb  1 20:15:03 aj-ThinkPad-E450 Fledge[28176] INFO: scheduler: fledge.services.core.scheduler.scheduler: Schedule 'HTC' is not enabled



    {
      "name": "HTC",
      "type": "Northbound",
      "address": "localhost",
      "management_port": 38103,
      "service_port": null,
      "protocol": "http",
      "status": "failed"
    }


```

**Comment by MarkRiddoch** [comment]
Fixed the corner case for having Neve sent any data. However HTTPC North has an issue with the new SimpleWebServer library that causes that plugin to fail in the plugin itself. FOGL-4965 raised to fix the HTTPC north plugin.

**Review by pintomax — APPROVED** [review]

**Comment by ashish-jabble** [comment]
@MarkRiddoch I am not sure what you have fixed in your last commit. And I re-ran above steps and both cases are still not resolved. let me know what I need to test with this further.
With OMF plugin it seems to be okay.

**Comment by MarkRiddoch** [comment]
HTTP North has a separate bug that is in the SimpleWebServer library and will not work, it is unrelated to the service, it silly fails to shutdown in the plugin. The OMF plugin and the OPCUA north can both be used to show the service side of this works. Testing with HTTP North only shows up the problem in the plugin.

**Review by ashish-jabble — APPROVED** [review]
Except `http-c` north plugin (known issue), issue seems to be resolved with other plugins.

**Pull request merged**
