### PR TITLE
For the South plugin examples, fix the API signatures, use the approp…

### PR DESCRIPTION
**Pull request by mbourhis**
…riate C++ 'cast' operator

Keep consistency with the North plugin API,
by using 'PLUGIN_HANDLE' and not 'PLUGIN_HANDLE *'.

Use the appropriate C++ 'cast' operator, less permissive than the C cast operator.

The DHT11 South plugin (used as example in this documentation) is also updated: https://github.com/fledge-iot/fledge-south-dht/pull/23

Signed-off-by: Mikael Bourhis <mikael.bourhis@smile.fr>

### CODE REVIEW

**Review by MarkRiddoch — APPROVED** [review]

**Comment by mbourhis** [comment]
Hi,
this commit about 'fixing C++ South example in documentation'
is now up to date, with the 'develop' branch.

**Review by pintomax — DISMISSED** [review]

**Comment by RVerhoeff** [comment]
I agree with these changes with one exception: _plugin_reconfigure_ is specifically defined using “_PLUGIN_HANDLE *_” instead of "_PLUGIN_HANDLE_." I am referencing file _$FLEDGE_ROOT/C/services/south/include/south_plugin.h_ which defines the function pointers loaded by the South service. I have made the mistake of coding all plugins using _PLUGIN_HANDLE_ but the plugin then crashes on reconfiguration. Good point on the use of _static_cast_ instead of the standard C++ cast. Defining _plugin_reconfigure(PLUGIN_HANDLE *)_ and coding _static_cast<MyClass *>(*handle)_ does work.

**Comment by mbourhis** [comment]
Hi,
@RVerhoeff  thank you for your very relevant note. You are entirely right.
I have done the test on my own, and read carefully the signatures of the function pointers ($FLEDGE_ROOT/C/services/south/include/south_plugin.h).

I have fixed my mistake,
and added a new commit about the same subject, but for another documentation page: 'plugin_developers_guide/02_writing_plugins.html'.

Thank you all for your proofreading. 

PS: I also create the corresponding fix for the 'real' south-dht plugin (https://github.com/fledge-iot/fledge-south-dht/pull/25). Please, consider it too.

**Review by MarkRiddoch — APPROVED** [review]

**Comment by mbourhis** [comment]
Hi, I have just rebase my branch on 'develop' . Now, it is up to date.
Thanks for your review, the last one :)

**Review by MarkRiddoch — APPROVED** [review]

**Review by RVerhoeff — APPROVED** [review]

**Comment by mbourhis** [comment]
Hi @MarkRiddoch , @RVerhoeff

this branch is up-to-date now,
but as an external developer I do not have access to the 'Unit Test'  platform to perform the 'check' steps.
(but this PR is about 'documentation' only).

Is this PR OK for you?
Can this PR be integrated/merged by a person who has the 'write' access?

Thank you, have a nice day.

**Comment by mbourhis** [comment]
Too old PR,
a new one, up to date will be open.

**Pull request closed without merging**
