### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by kapokasa**
Updating direct link to fledge channel on slack.
This is my commit message

Signed-off-by: Daniel Lazaro <dlazaro@osisoft.com>

### CODE REVIEW

**Comment by MarkRiddoch** [comment]
Please update the DCO to allow this to be merge.

**Comment by kapokasa** [comment]
I do not  have a local branch...

**Comment by kapokasa** [comment]
This is my commit message

Signed-off-by: Daniel Lazaro <dlazaro@osisoft.com>

**Comment by MarkRiddoch** [comment]
Hi Daniel. I did the DCO sign-off bit on your latest PR. I'll close the d others.

**Comment by kapokasa** [comment]
Thanks!

**Pull request closed without merging**
