### PR TITLE
FOGL-7861: Memory growth on north service for DICT and LIST readings.

### PR DESCRIPTION
**Pull request by cyberwalk3r**
For north Python plugins, when converting T_DP_DICT/T_DP_LIST readings to PyObject, new DICT/LIST is being created for each datapoint.

### CODE REVIEW

**Comment by AmandeepArora** [comment]
> For north Python plugins, when converting T_DP_DICT/T_DP_LIST readings to PyObject, new DICT/LIST is being created for each datapoint.

This would be true for south service also?

**Comment by cyberwalk3r** [comment]
> > For north Python plugins, when converting T_DP_DICT/T_DP_LIST readings to PyObject, new DICT/LIST is being created for each datapoint.
> 
> This would be true for south service also?

No this would not be applicable to south service, in case of south service PyObject is converted to DatapointValue. (func getDatapointValue)

**Comment by AmandeepArora** [comment]
> > > For north Python plugins, when converting T_DP_DICT/T_DP_LIST readings to PyObject, new DICT/LIST is being created for each datapoint.
> > 
> > 
> > This would be true for south service also?
> 
> No this would not be applicable to south service, in case of south service PyObject is converted to DatapointValue. (func getDatapointValue)

On south side, this would be required when data has to be passed thru' a python filter next.

**Comment by AmandeepArora** [comment]
And with the code before the fix, it is not just a matter of memory leak, it would also have been incorrect behavior. i.e. convertDatapoint() would be returning only the last PyDict/PyList in case of multiple list/dict items.

**Review by AmandeepArora — APPROVED** [review]
Looks good.

**Comment by praveen-garg** [comment]
> > > > For north Python plugins, when converting T_DP_DICT/T_DP_LIST readings to PyObject, new DICT/LIST is being created for each datapoint.
> 
> > > 
> 
> > > 
> 
> > > This would be true for south service also?
> 
> > 
> 
> > No this would not be applicable to south service, in case of south service PyObject is converted to DatapointValue. (func getDatapointValue)
> 
> 
> 
> On south side, this would be required when data has to be passed thru' a python filter next.

@AmandeepArora Should a Jira be logged for this?

**Comment by AmandeepArora** [comment]
> > > > > For north Python plugins, when converting T_DP_DICT/T_DP_LIST readings to PyObject, new DICT/LIST is being created for each datapoint.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > This would be true for south service also?
> > 
> > 
> > > 
> > 
> > 
> > > No this would not be applicable to south service, in case of south service PyObject is converted to DatapointValue. (func getDatapointValue)
> > 
> > 
> > On south side, this would be required when data has to be passed thru' a python filter next.
> 
> @AmandeepArora Should a Jira be logged for this?

It seems similar problem would have occurred in south service + python filter case also, just need to verify it. There probably won't be any further code changes required.

**Review by MarkRiddoch — APPROVED** [review]

**Pull request merged**
