### PR TITLE
imagetest.py

### PR DESCRIPTION
**Pull request by Innovative-ashwin**
Signed-off-by: Innovative-ashwin <sinha.ashwini111@gmail.com>

### CODE REVIEW

**Review by YashTatkondawar — COMMENTED** [review]
We can remove tests/system/plugins/south/fledge-south-imagetest/python/fledge/plugins/south/imagetest as it is now moved to tests/system/python/fledge/plugins/south/imagetest. 

Also, do we need to keep https://github.com/fledge-iot/fledge/blob/FOGL-6361-imagetest/tests/system/python/fledge/plugins/south/imagetest/old?

**Comment by Innovative-ashwin** [comment]
> We can remove tests/system/plugins/south/fledge-south-imagetest/python/fledge/plugins/south/imagetest as it is now moved to tests/system/python/fledge/plugins/south/imagetest.
> 
> Also, do we need to keep https://github.com/fledge-iot/fledge/blob/FOGL-6361-imagetest/tests/system/python/fledge/plugins/south/imagetest/old?

Fixed

**Review by MarkRiddoch — APPROVED** [review]

**Review by YashTatkondawar — CHANGES_REQUESTED** [review]
@Innovative-ashwin The images are not properly displayed with 16-bit and 24-bit configuration, whereas it is good with 8-bit configuration. Please have a look.

16-bit image:
16bit_imagetest

24-bit image:
24bit_imagetest

**Review by YashTatkondawar — DISMISSED** [review]
Please fix the conflicts before merging the PR.

**Comment by Innovative-ashwin** [comment]
> Please fix the conflicts before merging the PR.

fixed

**Comment by Innovative-ashwin** [comment]
> @Innovative-ashwin The images are not properly displayed with 16-bit and 24-bit configuration, whereas it is good with 8-bit configuration. Please have a look.
> 
> 16-bit image: 16bit_imagetest
> 
> 24-bit image: 24bit_imagetest

Fixed

**Review by MarkRiddoch — CHANGES_REQUESTED** [review]
Could you please fix the DCO by signing your commit and also restrict the files to just the ones for the plugin.

**Review by YashTatkondawar — DISMISSED** [review]

**Comment by Innovative-ashwin** [comment]
> Could you please fix the DCO by signing your commit and also restrict the files to just the ones for the plugin.

DCO fixed and files changes consist of only my changes for the plugin

**Review by YashTatkondawar — APPROVED** [review]

**Comment by Innovative-ashwin** [comment]
> Could you please fix the DCO by signing your commit and also restrict the files to just the ones for the plugin.

Fixed

**Review by MarkRiddoch — APPROVED** [review]

**Pull request merged**
