### PR TITLE
Fogl 4546 : Asset entry not getting stored in db when number of assets are more than 135

### PR DESCRIPTION
**Pull request by sstefano69**
- the error is logged If it is not possible to attach a new DB and the row is skipped/not stored.

```
user.err, 3,1,Sep 24 09:55:02,localhost,Fledge, Storage[21530]: ERROR: attachNewDb - It was not possible to attach the db :/home/foglamp/Development/fledge/data/readings_10.db: to an idle connection, error :too many attached databases - max 10:
user.warning, 4,1,Sep 24 09:55:02,localhost,Fledge, Storage[21530]: WARNING: appendReadings - It was not possible to insert the row for the asset_code :perf_2_a133: into the readings, row ignored.
user.err, 3,1,Sep 24 09:55:02,localhost,Fledge, Storage[21530]: ERROR: attachNewDb - It was not possible to attach the db :/home/foglamp/Development/fledge/data/readings_10.db: to an idle connection, error :too many attached databases - max 10:
user.warning, 4,1,Sep 24 09:55:02,localhost,Fledge, Storage[21530]: WARNING: appendReadings - It was not possible to insert the row for the asset_code :perf_2_a134: into the readings, row ignored.
user.err, 3,1,Sep 24 09:55:06,localhost,Fledge, Storage[21530]: ERROR: attachNewDb - It was not possible to attach the db :/home/foglamp/Development/fledge/data/readings_10.db: to an idle connection, error :too many attached databases - max 10:
user.warning, 4,1,Sep 24 09:55:06,localhost,Fledge, Storage[21530]: WARNING: appendReadings - It was not possible to insert the row for the asset_code :perf_2_a135: into the readings, row ignored.
user.err, 3,1,Sep 24 09:55:06,localhost,Fledge, Storage[21530]: ERROR: attachNewDb - It was not possible to attach the db :/home/foglamp/Development/fledge/data/readings_10.db: to an idle connection, error :too many attached databases - max 10:
user.warning, 4,1,Sep 24 09:55:06,localhost,Fledge, Storage[21530]: WARNING: appendReadings - It was not possible to insert the row for the asset_code :perf_2_a136: into the readings, row ignored.
user.err, 3,1,Sep 24 09:55:06,localhost,Fledge, Storage[21530]: ERROR: attachNewDb - It was not possible to attach the db :/home/foglamp/Development/fledge/data/readings_10.db: to an idle connection, error :too many attached databases - max 10:
user.warning, 4,1,Sep 24 09:55:06,localhost,Fledge, Storage[21530]: WARNING: appendReadings - It was not possible to insert the row for the asset_code :perf_2_a137: into the readings, row ignored.
user.err, 3,1,Sep 24 09:55:06,localhost,Fledge, Storage[21530]: ERROR: attachNewDb - It was not possible to attach the db :/home/foglamp/Development/fledge/data/readings_10.db: to an idle connection, error :too many attached databases - max 10:
user.warning, 4,1,Sep 24 09:55:06,localhost,Fledge, Storage[21530]: WARNING: appendReadings - It was not possible to insert the row for the asset_code :perf_2_a138: into the readings, row ignored.
user.err, 3,1,Sep 24 09:55:10,localhost,Fledge, Storage[21530]: ERROR: attachNewDb - It was not possible to attach the db :/home/foglamp/Development/fledge/data/readings_10.db: to an idle connection, error :too many attached databases - max 10:
user.warning, 4,1,Sep 24 09:55:10,localhost,Fledge, Storage[21530]: WARNING: appendReadings - It was not possible to insert the row for the asset_code :perf_2_a139: into the readings, row ignored.
user.err, 3,1,Sep 24 09:55:10,localhost,Fledge, Storage[21530]: ERROR: attachNewDb - It was not possible to attach the db :/home/foglamp/Development/fledge/data/readings_10.db: to an idle connection, error :too many attached databases - max 10:
user.warning, 4,1,Sep 24 09:55:10,localhost,Fledge, Storage[21530]: WARNING: appendReadings - It was not possible to insert the row for the asset_code :perf_2_a140: into the readings, row ignored.

```

this behavour will be improved with a future implementation a jira is already available

- the new db, for example readings_10.db, remains created and empty/not used.

### CODE REVIEW

**Review by MarkRiddoch — APPROVED** [review]
As discussed let's stick with this for now and have a longer term plan for a better solution.

**Review by YashTatkondawar — COMMENTED** [review]
1. Currently if more than 135 assets are created it still shows in GUI south page i.e. 136th, 137th ... assets are still visible in GUI's South page and its reading value is getting increased. So as we are not storing the readings in db, so shall we not display in GUI also?
2. Now as we are limiting assets to 135 in db, so in GUI shall we not limit the asset creation to 135?

**Comment by sstefano69** [comment]
> 1. Currently if more than 135 assets are created it still shows in GUI south page i.e. 136th, 137th ... assets are still visible in GUI's South page and its reading value is getting increased. So as we are not storing the readings in db, so shall we not display in GUI also?
> 2. Now as we are limiting assets to 135 in db, so in GUI shall we not limit the asset creation to 135?

I think the current behavior within the GUI is fine,
let have a feedback from @MarkRiddoch

**Comment by MarkRiddoch** [comment]
> > 1. Currently if more than 135 assets are created it still shows in GUI south page i.e. 136th, 137th ... assets are still visible in GUI's South page and its reading value is getting increased. So as we are not storing the readings in db, so shall we not display in GUI also?
These stats are ingress stats and not storage stats. It is possible that we store less than we ingress, for example if we filter data. 
> > 2. Now as we are limiting assets to 135 in db, so in GUI shall we not limit the asset creation to 135?
Ideally yes, however this is a short term solution until we add an improvement to allow more than 136 assets to be stored. Practically nobody is storing this many distinct assets currently.
> 
> I think the current behavior within the GUI is fine,
> let have a feedback from @MarkRiddoch

**Pull request merged**
