### PR TITLE
doc-1.9.1

### PR DESCRIPTION
**Pull request by joyshmitz**
ubuntu 2004 repository can be added

### CODE REVIEW

**Review by MarkRiddoch — APPROVED** [review]
Thank you for this, my apologies I did not see this sooner.

**Comment by joyshmitz** [comment]
I am glad to help

**Comment by ashish-jabble** [comment]
@MarkRiddoch We can close it out this as out of date as of current release.

**Comment by MarkRiddoch** [comment]
Changes merged via different branch in order to resolve conflicts.

**Pull request closed without merging**
